version: "2"
services:
  client:
    image: node:18-alpine
    restart: always
    ports:
      - "3535:3535"
    working_dir: /client/src/
    volumes:
      - ./client:/client/src/
    entrypoint: ["npm", "start"]
    links:
      - api
    networks:
      - webappnetwork
  api:
    container_name: app
    image: app
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
      target: base
    ports:
      - "3344:3344"
    volumes:
      - ./server:/api
      - /server/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: news
    expose:
      - 27017
    volumes:
      - ./data-node:/data/db
      # - ./scripts/seed.js:/docker-entrypoint-initdb.d/seed.js
    command: mongod --noauth
    networks:
      - webappnetwork
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
